
import pytest

# UNIT TEST: Check for HTML structure
@pytest.mark.unit
def test_contains_html():
    """Unit Test: Page contains <html> tag"""
    assert "<html" in '<p><!DOCTYPE html><br /><html lang="en"><br /><head><br />  <meta charset="UTF-8"><br />  <meta name="viewport" content="width=device-width, initial-scale=1.0"><br />  <title>Login Page</title><br />  <style><br />    body {<br />      font-family: Arial, sans-serif;<br />      background-color: #f0f2f5;<br />      display: flex;<br />      align-items: center;<br />      justify-content: center;<br />      height: 100vh;<br />    }<br />    .login-container {<br />      background-color: white;<br />      padding: 20px 40px;<br />      border-radius: 8px;<br />      box-shadow: 0 0 10px rgba(0,0,0,0.1);<br />    }<br />    input {<br />      width: 100%;<br />      padding: 10px;<br />      margin-top: 10px;<br />      margin-bottom: 20px;<br />    }<br />    button {<br />      width: 100%;<br />      padding: 10px;<br />      background-color: #007bff;<br />      border: none;<br />      color: white;<br />      font-weight: bold;<br />      cursor: pointer;<br />    }<br />  </style><br /></head><br /><body><br />  <div class="login-container"><br />    <h2>Login</h2><br />    <form><br />      <input type="email" placeholder="Email" required /><br />      <input type="password" placeholder="Password" required /><br />      <button type="submit">Sign In</button><br />    </form><br />  </div><br /></body><br /></html></p>'

# UNIT TEST: Check for <form> element
@pytest.mark.unit
def test_contains_form():
    """Unit Test: Page contains <form> tag"""
    assert "<form" in '<p><!DOCTYPE html><br /><html lang="en"><br /><head><br />  <meta charset="UTF-8"><br />  <meta name="viewport" content="width=device-width, initial-scale=1.0"><br />  <title>Login Page</title><br />  <style><br />    body {<br />      font-family: Arial, sans-serif;<br />      background-color: #f0f2f5;<br />      display: flex;<br />      align-items: center;<br />      justify-content: center;<br />      height: 100vh;<br />    }<br />    .login-container {<br />      background-color: white;<br />      padding: 20px 40px;<br />      border-radius: 8px;<br />      box-shadow: 0 0 10px rgba(0,0,0,0.1);<br />    }<br />    input {<br />      width: 100%;<br />      padding: 10px;<br />      margin-top: 10px;<br />      margin-bottom: 20px;<br />    }<br />    button {<br />      width: 100%;<br />      padding: 10px;<br />      background-color: #007bff;<br />      border: none;<br />      color: white;<br />      font-weight: bold;<br />      cursor: pointer;<br />    }<br />  </style><br /></head><br /><body><br />  <div class="login-container"><br />    <h2>Login</h2><br />    <form><br />      <input type="email" placeholder="Email" required /><br />      <input type="password" placeholder="Password" required /><br />      <button type="submit">Sign In</button><br />    </form><br />  </div><br /></body><br /></html></p>'

# INTEGRATION TEST: Check for <input> fields
@pytest.mark.integration
def test_contains_input():
    """Integration Test: Page contains <input> tag"""
    assert "<input" in '<p><!DOCTYPE html><br /><html lang="en"><br /><head><br />  <meta charset="UTF-8"><br />  <meta name="viewport" content="width=device-width, initial-scale=1.0"><br />  <title>Login Page</title><br />  <style><br />    body {<br />      font-family: Arial, sans-serif;<br />      background-color: #f0f2f5;<br />      display: flex;<br />      align-items: center;<br />      justify-content: center;<br />      height: 100vh;<br />    }<br />    .login-container {<br />      background-color: white;<br />      padding: 20px 40px;<br />      border-radius: 8px;<br />      box-shadow: 0 0 10px rgba(0,0,0,0.1);<br />    }<br />    input {<br />      width: 100%;<br />      padding: 10px;<br />      margin-top: 10px;<br />      margin-bottom: 20px;<br />    }<br />    button {<br />      width: 100%;<br />      padding: 10px;<br />      background-color: #007bff;<br />      border: none;<br />      color: white;<br />      font-weight: bold;<br />      cursor: pointer;<br />    }<br />  </style><br /></head><br /><body><br />  <div class="login-container"><br />    <h2>Login</h2><br />    <form><br />      <input type="email" placeholder="Email" required /><br />      <input type="password" placeholder="Password" required /><br />      <button type="submit">Sign In</button><br />    </form><br />  </div><br /></body><br /></html></p>'

# INTEGRATION TEST: Check for <button> element
@pytest.mark.integration
def test_contains_button():
    """Integration Test: Page contains <button> tag"""
    assert "<button" in '<p><!DOCTYPE html><br /><html lang="en"><br /><head><br />  <meta charset="UTF-8"><br />  <meta name="viewport" content="width=device-width, initial-scale=1.0"><br />  <title>Login Page</title><br />  <style><br />    body {<br />      font-family: Arial, sans-serif;<br />      background-color: #f0f2f5;<br />      display: flex;<br />      align-items: center;<br />      justify-content: center;<br />      height: 100vh;<br />    }<br />    .login-container {<br />      background-color: white;<br />      padding: 20px 40px;<br />      border-radius: 8px;<br />      box-shadow: 0 0 10px rgba(0,0,0,0.1);<br />    }<br />    input {<br />      width: 100%;<br />      padding: 10px;<br />      margin-top: 10px;<br />      margin-bottom: 20px;<br />    }<br />    button {<br />      width: 100%;<br />      padding: 10px;<br />      background-color: #007bff;<br />      border: none;<br />      color: white;<br />      font-weight: bold;<br />      cursor: pointer;<br />    }<br />  </style><br /></head><br /><body><br />  <div class="login-container"><br />    <h2>Login</h2><br />    <form><br />      <input type="email" placeholder="Email" required /><br />      <input type="password" placeholder="Password" required /><br />      <button type="submit">Sign In</button><br />    </form><br />  </div><br /></body><br /></html></p>'

# E2E TEST: Check for <title> element
@pytest.mark.e2e
def test_contains_title():
    """E2E Test: Page contains <title> tag"""
    assert "<title" in '<p><!DOCTYPE html><br /><html lang="en"><br /><head><br />  <meta charset="UTF-8"><br />  <meta name="viewport" content="width=device-width, initial-scale=1.0"><br />  <title>Login Page</title><br />  <style><br />    body {<br />      font-family: Arial, sans-serif;<br />      background-color: #f0f2f5;<br />      display: flex;<br />      align-items: center;<br />      justify-content: center;<br />      height: 100vh;<br />    }<br />    .login-container {<br />      background-color: white;<br />      padding: 20px 40px;<br />      border-radius: 8px;<br />      box-shadow: 0 0 10px rgba(0,0,0,0.1);<br />    }<br />    input {<br />      width: 100%;<br />      padding: 10px;<br />      margin-top: 10px;<br />      margin-bottom: 20px;<br />    }<br />    button {<br />      width: 100%;<br />      padding: 10px;<br />      background-color: #007bff;<br />      border: none;<br />      color: white;<br />      font-weight: bold;<br />      cursor: pointer;<br />    }<br />  </style><br /></head><br /><body><br />  <div class="login-container"><br />    <h2>Login</h2><br />    <form><br />      <input type="email" placeholder="Email" required /><br />      <input type="password" placeholder="Password" required /><br />      <button type="submit">Sign In</button><br />    </form><br />  </div><br /></body><br /></html></p>'

# ACCESSIBILITY TEST: Check for lang attribute
@pytest.mark.accessibility
def test_html_lang():
    """Accessibility Test: <html> tag has lang attribute"""
    assert "lang=" in '<p><!DOCTYPE html><br /><html lang="en"><br /><head><br />  <meta charset="UTF-8"><br />  <meta name="viewport" content="width=device-width, initial-scale=1.0"><br />  <title>Login Page</title><br />  <style><br />    body {<br />      font-family: Arial, sans-serif;<br />      background-color: #f0f2f5;<br />      display: flex;<br />      align-items: center;<br />      justify-content: center;<br />      height: 100vh;<br />    }<br />    .login-container {<br />      background-color: white;<br />      padding: 20px 40px;<br />      border-radius: 8px;<br />      box-shadow: 0 0 10px rgba(0,0,0,0.1);<br />    }<br />    input {<br />      width: 100%;<br />      padding: 10px;<br />      margin-top: 10px;<br />      margin-bottom: 20px;<br />    }<br />    button {<br />      width: 100%;<br />      padding: 10px;<br />      background-color: #007bff;<br />      border: none;<br />      color: white;<br />      font-weight: bold;<br />      cursor: pointer;<br />    }<br />  </style><br /></head><br /><body><br />  <div class="login-container"><br />    <h2>Login</h2><br />    <form><br />      <input type="email" placeholder="Email" required /><br />      <input type="password" placeholder="Password" required /><br />      <button type="submit">Sign In</button><br />    </form><br />  </div><br /></body><br /></html></p>'

# SECURITY TEST: Check for password input
@pytest.mark.security
def test_password_input():
    """Security Test: Page contains password input field"""
    assert "type="password"" in '<p><!DOCTYPE html><br /><html lang="en"><br /><head><br />  <meta charset="UTF-8"><br />  <meta name="viewport" content="width=device-width, initial-scale=1.0"><br />  <title>Login Page</title><br />  <style><br />    body {<br />      font-family: Arial, sans-serif;<br />      background-color: #f0f2f5;<br />      display: flex;<br />      align-items: center;<br />      justify-content: center;<br />      height: 100vh;<br />    }<br />    .login-container {<br />      background-color: white;<br />      padding: 20px 40px;<br />      border-radius: 8px;<br />      box-shadow: 0 0 10px rgba(0,0,0,0.1);<br />    }<br />    input {<br />      width: 100%;<br />      padding: 10px;<br />      margin-top: 10px;<br />      margin-bottom: 20px;<br />    }<br />    button {<br />      width: 100%;<br />      padding: 10px;<br />      background-color: #007bff;<br />      border: none;<br />      color: white;<br />      font-weight: bold;<br />      cursor: pointer;<br />    }<br />  </style><br /></head><br /><body><br />  <div class="login-container"><br />    <h2>Login</h2><br />    <form><br />      <input type="email" placeholder="Email" required /><br />      <input type="password" placeholder="Password" required /><br />      <button type="submit">Sign In</button><br />    </form><br />  </div><br /></body><br /></html></p>'
