import pytest
@pytest.mark.integration
def test_contains_form():
    """Integration Test: Checks if the page contains a <form> element"""
    assert "<form" in """<!DOCTYPE html><html lang="en"><head>  <meta charset="UTF-8">  <meta name="viewport" content="width=device-width, initial-scale=1.0">  <title>Login Page</title>  <style>    body {      font-family: Arial, sans-serif;      background-color: #f0f2f5;      display: flex;      align-items: center;      justify-content: center;      height: 100vh;    }    .login-container {      background-color: white;      padding: 20px 40px;      border-radius: 8px;      box-shadow: 0 0 10px rgba(0,0,0,0.1);    }    input {      width: 100%;      padding: 10px;      margin-top: 10px;      margin-bottom: 20px;    }    button {      width: 100%;      padding: 10px;      background-color: #007bff;      border: none;      color: white;      font-weight: bold;      cursor: pointer;    }  </style></head><body>  <div class="login-container">    <h2>Login</h2>    <form>      <input type="email" placeholder="Email" required />      <input type="password" placeholder="Password" required />      <button type="submit">Sign In</button>    </form>  </div></body></html>"""

@pytest.mark.unit
def test_contains_input():
    """Unit Test: Checks if the page contains an <input> element"""
    assert "<input" in """<!DOCTYPE html><html lang="en"><head>  <meta charset="UTF-8">  <meta name="viewport" content="width=device-width, initial-scale=1.0">  <title>Login Page</title>  <style>    body {      font-family: Arial, sans-serif;      background-color: #f0f2f5;      display: flex;      align-items: center;      justify-content: center;      height: 100vh;    }    .login-container {      background-color: white;      padding: 20px 40px;      border-radius: 8px;      box-shadow: 0 0 10px rgba(0,0,0,0.1);    }    input {      width: 100%;      padding: 10px;      margin-top: 10px;      margin-bottom: 20px;    }    button {      width: 100%;      padding: 10px;      background-color: #007bff;      border: none;      color: white;      font-weight: bold;      cursor: pointer;    }  </style></head><body>  <div class="login-container">    <h2>Login</h2>    <form>      <input type="email" placeholder="Email" required />      <input type="password" placeholder="Password" required />      <button type="submit">Sign In</button>    </form>  </div></body></html>"""

@pytest.mark.integration
def test_contains_button():
    """Integration Test: Checks if the page contains a <button> element"""
    assert "<button" in """<!DOCTYPE html><html lang="en"><head>  <meta charset="UTF-8">  <meta name="viewport" content="width=device-width, initial-scale=1.0">  <title>Login Page</title>  <style>    body {      font-family: Arial, sans-serif;      background-color: #f0f2f5;      display: flex;      align-items: center;      justify-content: center;      height: 100vh;    }    .login-container {      background-color: white;      padding: 20px 40px;      border-radius: 8px;      box-shadow: 0 0 10px rgba(0,0,0,0.1);    }    input {      width: 100%;      padding: 10px;      margin-top: 10px;      margin-bottom: 20px;    }    button {      width: 100%;      padding: 10px;      background-color: #007bff;      border: none;      color: white;      font-weight: bold;      cursor: pointer;    }  </style></head><body>  <div class="login-container">    <h2>Login</h2>    <form>      <input type="email" placeholder="Email" required />      <input type="password" placeholder="Password" required />      <button type="submit">Sign In</button>    </form>  </div></body></html>"""

@pytest.mark.e2e
def test_contains_title():
    """E2E Test: Checks if the page contains a <title> element"""
    assert "<title" in """<!DOCTYPE html><html lang="en"><head>  <meta charset="UTF-8">  <meta name="viewport" content="width=device-width, initial-scale=1.0">  <title>Login Page</title>  <style>    body {      font-family: Arial, sans-serif;      background-color: #f0f2f5;      display: flex;      align-items: center;      justify-content: center;      height: 100vh;    }    .login-container {      background-color: white;      padding: 20px 40px;      border-radius: 8px;      box-shadow: 0 0 10px rgba(0,0,0,0.1);    }    input {      width: 100%;      padding: 10px;      margin-top: 10px;      margin-bottom: 20px;    }    button {      width: 100%;      padding: 10px;      background-color: #007bff;      border: none;      color: white;      font-weight: bold;      cursor: pointer;    }  </style></head><body>  <div class="login-container">    <h2>Login</h2>    <form>      <input type="email" placeholder="Email" required />      <input type="password" placeholder="Password" required />      <button type="submit">Sign In</button>    </form>  </div></body></html>"""

@pytest.mark.accessibility
def test_html_lang():
    """Accessibility Test: Checks if the <html> tag has a lang attribute"""
    assert "lang=" in """<!DOCTYPE html><html lang="en"><head>  <meta charset="UTF-8">  <meta name="viewport" content="width=device-width, initial-scale=1.0">  <title>Login Page</title>  <style>    body {      font-family: Arial, sans-serif;      background-color: #f0f2f5;      display: flex;      align-items: center;      justify-content: center;      height: 100vh;    }    .login-container {      background-color: white;      padding: 20px 40px;      border-radius: 8px;      box-shadow: 0 0 10px rgba(0,0,0,0.1);    }    input {      width: 100%;      padding: 10px;      margin-top: 10px;      margin-bottom: 20px;    }    button {      width: 100%;      padding: 10px;      background-color: #007bff;      border: none;      color: white;      font-weight: bold;      cursor: pointer;    }  </style></head><body>  <div class="login-container">    <h2>Login</h2>    <form>      <input type="email" placeholder="Email" required />      <input type="password" placeholder="Password" required />      <button type="submit">Sign In</button>    </form>  </div></body></html>"""

@pytest.mark.security
def test_password_input():
    """Security Test: Checks if the page contains a password input field"""
    assert "type="password"" in """<!DOCTYPE html><html lang="en"><head>  <meta charset="UTF-8">  <meta name="viewport" content="width=device-width, initial-scale=1.0">  <title>Login Page</title>  <style>    body {      font-family: Arial, sans-serif;      background-color: #f0f2f5;      display: flex;      align-items: center;      justify-content: center;      height: 100vh;    }    .login-container {      background-color: white;      padding: 20px 40px;      border-radius: 8px;      box-shadow: 0 0 10px rgba(0,0,0,0.1);    }    input {      width: 100%;      padding: 10px;      margin-top: 10px;      margin-bottom: 20px;    }    button {      width: 100%;      padding: 10px;      background-color: #007bff;      border: none;      color: white;      font-weight: bold;      cursor: pointer;    }  </style></head><body>  <div class="login-container">    <h2>Login</h2>    <form>      <input type="email" placeholder="Email" required />      <input type="password" placeholder="Password" required />      <button type="submit">Sign In</button>    </form>  </div></body></html>"""
